name: irane_ma
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.3+1
  flutter_svg: ^2.0.10+1
  logger: ^2.3.0
  connectivity_plus: ^6.0.3
  carousel_slider:
    path: ../irane_ma/packages/flutter_carousel_slider-master_4.2
  interactable_svg: ^0.0.7
  responsive_sizer: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/yekan_bakh/YEKAN_BAKH_EN_03_LIGHT.ttf
          weight: 300
        - asset: assets/fonts/yekan_bakh/YEKAN_BAKH_EN_04_REGULAR.ttf
          weight: 400
        - asset: assets/fonts/yekan_bakh/YEKAN_BAKH_EN_05_MEDIUM.ttf
          weight: 500
        - asset: assets/fonts/yekan_bakh/YEKAN_BAKH_EN_06_BOLD.ttf
          weight: 600
        - asset: assets/fonts/yekan_bakh/YEKAN_BAKH_EN_08_FAT.ttf
          weight: 700
        - asset: assets/fonts/yekan_bakh/YEKAN_BAKH_EN_07_HEAVY.ttf
          weight: 800
    - family: AdobeArabic
      fonts:
        - asset: assets/fonts/adobe_arabic/AdobeArabic_Bold.ttf
          weight: 600